# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from sepp.v1 import queue_pb2 as sepp_dot_v1_dot_queue__pb2


class QueueServiceStub(object):
    """============================================================================
    Service definitions
    ============================================================================

    Authentication: when the server is configured with API keys, every RPC
    requires an `authorization` metadata header of the form `Bearer <api key>`.
    Requests with a missing or invalid key fail with UNAUTHENTICATED.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnqueueBatch = channel.unary_unary(
                '/sepp.v1.QueueService/EnqueueBatch',
                request_serializer=sepp_dot_v1_dot_queue__pb2.EnqueueBatchRequest.SerializeToString,
                response_deserializer=sepp_dot_v1_dot_queue__pb2.EnqueueBatchResponse.FromString,
                _registered_method=True)
        self.EnqueueAtomic = channel.unary_unary(
                '/sepp.v1.QueueService/EnqueueAtomic',
                request_serializer=sepp_dot_v1_dot_queue__pb2.EnqueueBatchRequest.SerializeToString,
                response_deserializer=sepp_dot_v1_dot_queue__pb2.EnqueueAtomicResponse.FromString,
                _registered_method=True)
        self.Reserve = channel.unary_unary(
                '/sepp.v1.QueueService/Reserve',
                request_serializer=sepp_dot_v1_dot_queue__pb2.ReserveRequest.SerializeToString,
                response_deserializer=sepp_dot_v1_dot_queue__pb2.ReserveResponse.FromString,
                _registered_method=True)
        self.Ack = channel.unary_unary(
                '/sepp.v1.QueueService/Ack',
                request_serializer=sepp_dot_v1_dot_queue__pb2.AckRequest.SerializeToString,
                response_deserializer=sepp_dot_v1_dot_queue__pb2.AckResponse.FromString,
                _registered_method=True)
        self.Nack = channel.unary_unary(
                '/sepp.v1.QueueService/Nack',
                request_serializer=sepp_dot_v1_dot_queue__pb2.NackRequest.SerializeToString,
                response_deserializer=sepp_dot_v1_dot_queue__pb2.NackResponse.FromString,
                _registered_method=True)
        self.Extend = channel.unary_unary(
                '/sepp.v1.QueueService/Extend',
                request_serializer=sepp_dot_v1_dot_queue__pb2.ExtendRequest.SerializeToString,
                response_deserializer=sepp_dot_v1_dot_queue__pb2.ExtendResponse.FromString,
                _registered_method=True)
        self.DrainDeadLetters = channel.unary_unary(
                '/sepp.v1.QueueService/DrainDeadLetters',
                request_serializer=sepp_dot_v1_dot_queue__pb2.DrainDeadLettersRequest.SerializeToString,
                response_deserializer=sepp_dot_v1_dot_queue__pb2.DrainDeadLettersResponse.FromString,
                _registered_method=True)
        self.GetServerInfo = channel.unary_unary(
                '/sepp.v1.QueueService/GetServerInfo',
                request_serializer=sepp_dot_v1_dot_queue__pb2.GetServerInfoRequest.SerializeToString,
                response_deserializer=sepp_dot_v1_dot_queue__pb2.GetServerInfoResponse.FromString,
                _registered_method=True)


class QueueServiceServicer(object):
    """============================================================================
    Service definitions
    ============================================================================

    Authentication: when the server is configured with API keys, every RPC
    requires an `authorization` metadata header of the form `Bearer <api key>`.
    Requests with a missing or invalid key fail with UNAUTHENTICATED.
    """

    def EnqueueBatch(self, request, context):
        """Best-effort batch enqueue. Accepts multiple jobs in one request and
        returns an individual success or rejection per job. Use this for
        fan-out batches of independent jobs where partial success is fine.

        Whole-batch failures use gRPC status codes:
        INVALID_ARGUMENT  - batch shape is malformed (empty, exceeds max_enqueue_batch)
        UNAUTHENTICATED   - missing or invalid API key
        INTERNAL          - server-side storage failure. Transient, but a retry
        may duplicate jobs that carry no idempotency_key.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnqueueAtomic(self, request, context):
        """Atomic batch enqueue. Either every job is enqueued or none are.

        Use this when the jobs are coordinated steps and partial success would
        leave the system in an inconsistent state.

        gRPC status codes:
        INVALID_ARGUMENT  - batch shape is malformed (empty, exceeds max_enqueue_batch)
        UNAUTHENTICATED   - missing or invalid API key
        INTERNAL          - server-side storage failure. Transient, but a retry
        may duplicate jobs that carry no idempotency_key.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reserve(self, request, context):
        """Long-poll reserve. Returns zero or more jobs, or times out with an empty list.

        gRPC status codes:
        INVALID_ARGUMENT     - request shape is malformed
        FAILED_PRECONDITION  - server is in strict mode and one or more requested
        queues are not declared
        UNAUTHENTICATED      - missing or invalid API key
        INTERNAL             - server-side storage failure
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ack(self, request, context):
        """Acknowledge successful completion of a job.

        gRPC status codes:
        INVALID_ARGUMENT     - request shape is malformed
        NOT_FOUND            - no in-flight job with this id (already acked,
        lease expired and was reassigned, or never existed)
        FAILED_PRECONDITION  - the attempt number does not match the current
        in-flight attempt (lease was reassigned)
        UNAUTHENTICATED      - missing or invalid API key
        INTERNAL             - server-side storage failure
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Nack(self, request, context):
        """Negative-acknowledge with retry directive. Same status codes as Ack.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Extend(self, request, context):
        """Extend the lease on an in-flight job. Same status codes as Ack.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DrainDeadLetters(self, request, context):
        """Drain dead-lettered jobs for inspection and manual replay.

        Returns up to `max` DeadLetterRecords (oldest-first, optionally filtered to
        a single queue) and REMOVES them from the server in the same transaction
        before responding. This is destructive and privileged: there is no
        redelivery token (unlike Reserve/Ack), so a dropped response permanently
        removes the jobs.

        An empty list means nothing matched, which is indistinguishable from
        dead-letter retention being disabled — check dead_letter_retention_enabled
        in GetServerInfo.

        gRPC status codes:
        INVALID_ARGUMENT  - request shape is malformed
        UNAUTHENTICATED   - missing or invalid API key
        INTERNAL          - server-side storage failure
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerInfo(self, request, context):
        """Get server info and capabilities. INTERNAL on storage failure; otherwise infallible.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueueServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnqueueBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.EnqueueBatch,
                    request_deserializer=sepp_dot_v1_dot_queue__pb2.EnqueueBatchRequest.FromString,
                    response_serializer=sepp_dot_v1_dot_queue__pb2.EnqueueBatchResponse.SerializeToString,
            ),
            'EnqueueAtomic': grpc.unary_unary_rpc_method_handler(
                    servicer.EnqueueAtomic,
                    request_deserializer=sepp_dot_v1_dot_queue__pb2.EnqueueBatchRequest.FromString,
                    response_serializer=sepp_dot_v1_dot_queue__pb2.EnqueueAtomicResponse.SerializeToString,
            ),
            'Reserve': grpc.unary_unary_rpc_method_handler(
                    servicer.Reserve,
                    request_deserializer=sepp_dot_v1_dot_queue__pb2.ReserveRequest.FromString,
                    response_serializer=sepp_dot_v1_dot_queue__pb2.ReserveResponse.SerializeToString,
            ),
            'Ack': grpc.unary_unary_rpc_method_handler(
                    servicer.Ack,
                    request_deserializer=sepp_dot_v1_dot_queue__pb2.AckRequest.FromString,
                    response_serializer=sepp_dot_v1_dot_queue__pb2.AckResponse.SerializeToString,
            ),
            'Nack': grpc.unary_unary_rpc_method_handler(
                    servicer.Nack,
                    request_deserializer=sepp_dot_v1_dot_queue__pb2.NackRequest.FromString,
                    response_serializer=sepp_dot_v1_dot_queue__pb2.NackResponse.SerializeToString,
            ),
            'Extend': grpc.unary_unary_rpc_method_handler(
                    servicer.Extend,
                    request_deserializer=sepp_dot_v1_dot_queue__pb2.ExtendRequest.FromString,
                    response_serializer=sepp_dot_v1_dot_queue__pb2.ExtendResponse.SerializeToString,
            ),
            'DrainDeadLetters': grpc.unary_unary_rpc_method_handler(
                    servicer.DrainDeadLetters,
                    request_deserializer=sepp_dot_v1_dot_queue__pb2.DrainDeadLettersRequest.FromString,
                    response_serializer=sepp_dot_v1_dot_queue__pb2.DrainDeadLettersResponse.SerializeToString,
            ),
            'GetServerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerInfo,
                    request_deserializer=sepp_dot_v1_dot_queue__pb2.GetServerInfoRequest.FromString,
                    response_serializer=sepp_dot_v1_dot_queue__pb2.GetServerInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sepp.v1.QueueService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sepp.v1.QueueService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QueueService(object):
    """============================================================================
    Service definitions
    ============================================================================

    Authentication: when the server is configured with API keys, every RPC
    requires an `authorization` metadata header of the form `Bearer <api key>`.
    Requests with a missing or invalid key fail with UNAUTHENTICATED.
    """

    @staticmethod
    def EnqueueBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sepp.v1.QueueService/EnqueueBatch',
            sepp_dot_v1_dot_queue__pb2.EnqueueBatchRequest.SerializeToString,
            sepp_dot_v1_dot_queue__pb2.EnqueueBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnqueueAtomic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sepp.v1.QueueService/EnqueueAtomic',
            sepp_dot_v1_dot_queue__pb2.EnqueueBatchRequest.SerializeToString,
            sepp_dot_v1_dot_queue__pb2.EnqueueAtomicResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reserve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sepp.v1.QueueService/Reserve',
            sepp_dot_v1_dot_queue__pb2.ReserveRequest.SerializeToString,
            sepp_dot_v1_dot_queue__pb2.ReserveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sepp.v1.QueueService/Ack',
            sepp_dot_v1_dot_queue__pb2.AckRequest.SerializeToString,
            sepp_dot_v1_dot_queue__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Nack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sepp.v1.QueueService/Nack',
            sepp_dot_v1_dot_queue__pb2.NackRequest.SerializeToString,
            sepp_dot_v1_dot_queue__pb2.NackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Extend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sepp.v1.QueueService/Extend',
            sepp_dot_v1_dot_queue__pb2.ExtendRequest.SerializeToString,
            sepp_dot_v1_dot_queue__pb2.ExtendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DrainDeadLetters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sepp.v1.QueueService/DrainDeadLetters',
            sepp_dot_v1_dot_queue__pb2.DrainDeadLettersRequest.SerializeToString,
            sepp_dot_v1_dot_queue__pb2.DrainDeadLettersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sepp.v1.QueueService/GetServerInfo',
            sepp_dot_v1_dot_queue__pb2.GetServerInfoRequest.SerializeToString,
            sepp_dot_v1_dot_queue__pb2.GetServerInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
